### ISSUE TITLE
Fix imports

### ISSUE THREAD

**Issue by pavel-kirienko** [Zubax/kucher#26]
Transform occurrences like this:

https://github.com/Zubax/kucher/blob/cedb1d9fff56d13539582923cf522d7d9a88f45c/kucher/view/main_window/register_view_widget/_mock_registers.py#L16

Into the correct form:

```python
from kucher.view.device_model_representation import Register
```

And get rid of the unnecessary `sys.path` manipulations in `__init__.py`.

**Comment by loicgilbert** [comment]
Should all imports be absolute imports?
e.g. should this:
https://github.com/Zubax/kucher/blob/b5acaae7289af9314879a5b27de9bfca44622633/kucher/view/main_window/register_view_widget/editor_delegate.py#L27
be replaced by `from kucher.view.main_window.register_view_widget.model import Model`?

**Comment by pavel-kirienko** [comment]
No, relative imports are OK, they do not violate the coding conventions.

**Comment by loicgilbert** [comment]
> And get rid of the unnecessary `sys.path` manipulations in `__init__.py`.

Which manipulations are unnecessary?

**Comment by pavel-kirienko** [comment]
Couldn't find those, perhaps I was mistaken about that part.

**Comment by pavel-kirienko** [comment]
Ah, found it. The module lookup path is configured outside the application:

https://github.com/Zubax/kucher/blob/80ec60bb7331566678ed56bf3ae6c6663cea013b/test_linux.sh#L2

This `PYTHONPATH=kucher` should no longer be necessary.
