### ISSUE TITLE
Multiple issues with dependencies

### ISSUE THREAD

**Issue by a6a3uh** [Zubax/kucher#3]
It seems like dependencies listed in `requirements.txt `are not enough. At least on Mac OSX. And probably on any clean system.

What I did to make some progress (I used `conda`) is as follows:

> conda create --name  kucher2 python=3.6 --no-default-packages

> source activate kucher2

> conda install pyqt

> conda install numpy

> conda install pytest

> conda install pyserial

> pip install quamash

> conda install cython

> pip install construct

And finally stuck with popcop missing or not working (producing Assert on import) if just plain copied with issue described [here](https://github.com/Zubax/popcop/issues/4).

Fixing that by just commenting line causing assertion I get to next [issue](https://github.com/Zubax/kucher/issues/5) with missing import in `popcop`.

**Comment by pavel-kirienko** [comment]
Yes, `requirements.txt` requires updating; I'm going to keep this open for now.

**Comment by a6a3uh** [comment]
I see `quamash` is a submodule dependency so could not be installed separately. Or could be removed from submodules. The same is for `construct`. It's submodule version is compatible with application while the latest one is [not](https://github.com/Zubax/kucher/issues/4).

**Comment by a6a3uh** [comment]
Btw. While app is running  in python 3.6.6. With python 3.7.0 it gives 

> Traceback (most recent call last):
>   File "./zubax-kucher", line 22, in <module>
>     sys.exit(main())
>   File "... kucher/kucher/main.py", line 45, in main
>     from quamash import QEventLoop
>   File "... kucher/kucher/libraries/quamash/quamash/__init__.py", line 275
>     future = asyncio.async(future, loop=self)
>                          ^
> SyntaxError: invalid syntax

**Comment by pavel-kirienko** [comment]
The stack trace you posted is incomplete.

**Comment by a6a3uh** [comment]
Sorry. Updated the message with full stack trace.
Editor removes indentation. Actually arrow is pointing on `async` word.

**Comment by pavel-kirienko** [comment]
Ah. Here is the culprit: https://docs.python.org/3.6/library/asyncio-task.html#asyncio.async. `async` is a reserved keyword starting with Python 3.7; that API function is deprecated since Python 3.4. I should update quamash to a newer version where this issue is fixed - this changeset was merged in just 4 days ago and is released under v0.6.1: https://github.com/harvimt/quamash/pull/94/files#diff-b6196c9cf4a2f8190164136b76096c05L275

**Comment by pavel-kirienko** [comment]
If you're keen on Python 3.7, perhaps you could submit a PR updating the quamash submodule? That would be appreciated.

**Comment by irieblue** [comment]
I am interested in getting this running on OSX. I am willing to help out. What is the latest on supporting OSX. Is there a recommended minimum version of python to target?

**Comment by pavel-kirienko** [comment]
> Is there a recommended minimum version of python to target?

Yes, Kucher requires Python 3.6. Let me know if you have further questions.
