### ISSUE TITLE
Make the message marshaller compatible with the latest version of Construct

### ISSUE THREAD

**Issue by a6a3uh** [Zubax/kucher#4]
Running stuff under clean `conda` python 3.6 environment gives the following. The setup process is described in other [issue](https://github.com/Zubax/kucher/issues/3).

> 2018-07-26 13:57:17,113 pid=4703  INFO: quamash: Using Qt Implementation: PyQt5
> Traceback (most recent call last):
>   File "./zubax-kucher", line 22, in <module>
>     sys.exit(main())
>   File "... kucher/kucher/main.py", line 47, in main
>     from .fuhrer import Fuhrer
>   File "... kucher/kucher/fuhrer/__init__.py", line 19, in <module>
>     from kucher.model import device_model
>   File "... kucher/kucher/model/device_model/__init__.py", line 19, in <module>
>     from .communicator import MessageType, Message
>   File "... kucher/kucher/model/device_model/communicator/__init__.py", line 17, in <module>
>     from .communicator import Communicator, CommunicationChannelClosedException, LOOPBACK_PORT_NAME, AnyMessage
>   File "... kucher/kucher/model/device_model/communicator/communicator.py", line 21, in <module>
>     from .messages import MessageType, Message, Codec
>   File "... kucher/kucher/model/device_model/communicator/messages.py", line 339, in <module>
>     'entries' / TaskStatisticsEntryFormatV1[7:8],
>   File "... miniconda3/envs/kucher2/lib/python3.6/site-packages/construct/core.py", line 672, in __getitem__
>     raise ConstructError("subcon[N] syntax can only be used for Arrays, use GreedyRange(subcon) instead?")
> construct.core.ConstructError: subcon[N] syntax can only be used for Arrays, use GreedyRange(subcon) instead?

What I did just to move further on to next issues is replaced line in `messages.py:339`

> 'entries' / TaskStatisticsEntryFormatV1[7:8],

by this 

> 'entries' / TaskIDFormat,

Chances this is not correct but this allowed to move on not thinking too much on the program's logic.

**Comment by pavel-kirienko** [comment]
You are using a wrong version of `construct`; please move back to an older one. Version 2.9.40 should work.

Breaking change: https://github.com/MostAwesomeDude/construct/pull/24/commits/5a4a671889e2a70a805e6265ac37d0a8eb3ff388
Another affected project: https://github.com/citruz/beacontools/issues/14

I am going to keep this issue open under a different name to make the code compatible with the new construct API later.

**Comment by a6a3uh** [comment]
After using 

> git submodule update --init --recursive

Correct version of construct is used. Not tested with ESC though as I don't have it available at the moment.

**Comment by Serious-Dave** [comment]
I'm trying to run from source on Windows also using Python 3.7. I've 'updated' to version 2.9.40 of `construct`, but still getting an error. Anyone able to shed some light?

> PS D:\...\BAMF\kucher-master> python zubax-kucher
> 2018-07-31 11:15:41,403 pid=3232  INFO: quamash: Using Qt Implementation: PyQt5
> Traceback (most recent call last):
>   File "zubax-kucher", line 22, in <module>
>   File "D:\...\BAMF\kucher-master\kucher\main.py", line 47, in main
>     from .fuhrer import Fuhrer
>   File "D:\...\BAMF\kucher-master\kucher\fuhrer\__init__.py", line 19, in <module>
>     from kucher.model import device_model
>   File "D:\...\BAMF\kucher-master\kucher\model\device_model\__init__.py", line 19, in <module>
>     from .communicator import MessageType, Message
>   File "D:\...\BAMF\kucher-master\kucher\model\device_model\communicator\__init__.py", line 17, in <module>
>     from .communicator import Communicator, CommunicationChannelClosedException, LOOPBACK_PORT_NAME, AnyMessage
>   File "D:\...\BAMF\kucher-master\kucher\model\device_model\communicator\communicator.py", line 21, in <module>
>     from .messages import MessageType, Message, Codec
>   File "D:\...\BAMF\kucher-master\kucher\model\device_model\communicator\messages.py", line 339, in <module>
>     'entries' / TaskStatisticsEntryFormatV1[7:8],
>   File "C:\Users\david\AppData\Local\Continuum\anaconda3\lib\site-packages\construct\core.py", line 645, in __getitem__
>     raise ValueError("slice can only be like X[:]")
> ValueError: slice can only be like X[:]
> PS D:\...\BAMF\kucher-master> pip show construct
> Name: construct
> Version: 2.9.40
> Summary: A powerful declarative symmetric parser/builder for binary data
> Home-page: http://construct.readthedocs.org
> Author: Arkadiusz Bulski, Tomer Filiba, Corbin Simpson
> Author-email: arek.bulski@gmail.com, tomerfiliba@gmail.com, MostAwesomeDude@gmail.com
> License: MIT
> Location: c:\users\david\appdata\local\continuum\anaconda3\lib\site-packages
> Requires:
> Required-by:

**Comment by pavel-kirienko** [comment]
You're not supposed to update Construct, go back to the default version.
Python 3.7 is not supported because of Quamash; if you really need to use
it, you're on your own.

**Comment by loicgilbert** [comment]
The new construct APIcreates creates errors that doesn’t seem fixable. I’m closing the issue, we will keep the old version of construct for now.
