### ISSUE TITLE
Update for compatibility with Python 3.10; update dependencies

### ISSUE THREAD

**Issue by pavel-kirienko** [Zubax/kucher#44]

**Comment by silverv** [comment]
Needs to have tests moved from Python 3.6 to 3.8 and 3.10.

**Comment by pavel-kirienko** [comment]
Let's do it. Examples on how to use AppVeyor:

https://github.com/UAVCAN/pyuavcan/blob/master/.appveyor.yml

https://github.com/UAVCAN/yakut/blob/master/.appveyor.yml
