### ISSUE TITLE
kucher tries to import NodeInfoMessage from popcop which seems to be missing

### ISSUE THREAD

**Issue by a6a3uh** [Zubax/kucher#5]
After dealing with [dependencies](https://github.com/Zubax/kucher/issues/3). And "fixing" registering [issues](https://github.com/Zubax/popcop/issues/4) with popcop by just commenting line 526 in register.py causing assert. I have error from `kucher` trying to import something missing within `popcop` library:

> kucher/kucher/model/device_model/device_info_view.py", line 15, in <module>
>     from popcop.standard import NodeInfoMessage
> ImportError: cannot import name 'NodeInfoMessage'

And I can't find any mentions of `NodeInfoMessage` that `kucher` tries to import from `popcop`.

**Comment by pavel-kirienko** [comment]
You are supposed to initialize the git submodules with `git submodule update --init --recursive` in order to pull in the right version of popcop, where the referred class is defined.

**Comment by a6a3uh** [comment]
Not noticed repo uses submodules. Now with submodules correct versions of `construct` and `popcop` are used. The app is running now.
