### ISSUE TITLE
Cannot connect to telega

### ISSUE THREAD

**Issue by suzonch** [Zubax/kucher#53]
![image](https://user-images.githubusercontent.com/26577218/197193435-a979aa90-14f1-4f7f-991e-5bb185270069.png)
![image](https://user-images.githubusercontent.com/26577218/197193477-8bdddce6-97af-4c6b-9781-62d60225697c.png)

**Comment by pavel-kirienko** [comment]
@suzonch please check this on v1.2 from the file server and close the issue if it is not reproducible.
